language: cpp
os:
- linux
- osx
- windows
osx_image: xcode14.2
addons:
  apt:
    packages:
    - libluajit-5.1-dev
    - libluajit-5.1-dev:i386
    - g++-multilib
filter_secrets: false
install:
- curl -u yancouto:$SDK_TOKEN -sL https://raw.githubusercontent.com/yancouto/private-steamworks-sdk/master/steamworks_sdk_158a.zip
  -o sdk.zip
- unzip -q sdk.zip
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2017-workload-vctools; fi
script:
- mkdir build
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then     make osx               && mv luasteam.so  build/osx_luasteam.so;     fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make linux64           && cp luasteam.so  build/linux64_luasteam.so; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make linux32           && cp luasteam.so  build/linux32_luasteam.so; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mingw32-make windows64 && cp luasteam.dll build/win64_luasteam.dll;  fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mingw32-make windows32 && cp luasteam.dll build/win32_luasteam.dll;  fi
deploy:
  provider: releases
  api_key:
    secure: "Z5xok8J7iaxOty9UMvMl3MgiSNHnHqMBAfufDtebvNAP4uQyJsTms+X430tKMxu0BFMylqZZHU74Q4cddemIMHvYu0p+PlMDLEUBGYCxJcTiUSAfCxLrE5gi4aqP0RCxb5gNyoyULDpGWiV9gvVZUp+Tnja/3S2GLjbAzBnWU6Ew62AMwnX3BWEfXvAgcX4xet0FqbreRC3L52Q+RNbSvl2diXEfZ0GATvJvbaXfRbdZgisgGwl3IC+Q9sl8hEab7PbkcBe6rLRh2bwIKzCYZf9KWUvziffYF8+dVYtNS2o9B1wrpRWOse8y6DwmbZWpLZXaGgZuaVIqnWOb7VuNdwytHc2U4l7yPB+1izHT9vbI83q8aE3KRReeHkdn2fwuhzhe9RJNcYUzLxUXXBlzr3Tt4pQNA5vSqoGTScJwwI89biX27j4pKwIvWgbl+zO5RlK3CqDtcNtVDC+5fjpWSlYvUExCvVvGrVHyEMC13z+8c2KtOktm14qFlTiYPTj0PLDH8DhnqjfzY1jsyKmnJ76pU6Fn89MUDqE73vatyjVyhKFZrEIS8I62z5wLhLeZ+twaLQ4Z38f0N2ukTezv5j27gS9ZGRjo6Bz3AyuFiTN5XaFv45sP+UiUafYYREdw7Z0B8C4Rk2otynWvFKqjE9V97hSNp4UOq8/mGP6EWjE="
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
    repo: uspgamedev/luasteam
